version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - common-net
    volumes:
      - ./:/build

networks:
  common-net:
    external: true